package org.taniwha.service;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

/**
 * Generates human-readable descriptions for columns and values using LLM text generation.
 * No hardcoded descriptions - all text is generated by LLM based on context.
 */
@Service
public class DescriptionGenerator {
    
    private static final Logger logger = LoggerFactory.getLogger(DescriptionGenerator.class);
    
    private final LLMTextGenerator llmTextGenerator;
    
    @Autowired
    public DescriptionGenerator(LLMTextGenerator llmTextGenerator) {
        this.llmTextGenerator = llmTextGenerator;
    }
    
    /**
     * Generate description for a column based on its name, sample values, and terminology.
     * Uses LLM to generate natural language description.
     * 
     * @param columnName The name of the column
     * @param terminology SNOMED CT terminology from Snowstorm (optional)
     * @param sampleValues Sample values from the column (optional)
     */
    public String generateColumnDescription(String columnName, String terminology, List<String> sampleValues) {
        try {
            return llmTextGenerator.generateColumnDescription(columnName, terminology, sampleValues);
        } catch (Exception e) {
            logger.warn("Failed to generate column description for '{}': {}", columnName, e.getMessage());
            return "";
        }
    }
    
    /**
     * Generate description for a specific value in the context of a column.
     * Uses LLM to generate context-aware description.
     * 
     * @param columnName The column this value belongs to
     * @param value The value to describe
     * @param min Minimum value in range (for numeric values), null for categorical
     * @param max Maximum value in range (for numeric values), null for categorical
     */
    public String generateValueDescription(String columnName, String value, String min, String max) {
        try {
            if (min != null && max != null) {
                // Numeric value with range context
                return llmTextGenerator.generateNumericValueDescription(columnName, value, min, max);
            } else {
                // Categorical value
                return llmTextGenerator.generateCategoricalValueDescription(columnName, value);
            }
        } catch (Exception e) {
            logger.warn("Failed to generate value description for '{}' in '{}': {}", value, columnName, e.getMessage());
            return "";
        }
    }
    
    /**
     * Clear the description cache
     */
    public void clearCache() {
        llmTextGenerator.clearCache();
    }
}

