version: '3.8'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      # run in NIOFS mode, skip vm.max_map_count check
      - node.store.allow_mmap=false
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/"]
      interval: 15s
      retries: 5

  snowstorm:
    image: snomedinternational/snowstorm:latest
    container_name: snowstorm
    depends_on:
      elasticsearch:
        condition: service_healthy
    entrypoint:
      - java
      - -Xms1g
      - -Xmx2g
      - --add-opens=java.base/java.lang=ALL-UNNAMED
      - --add-opens=java.base/java.util=ALL-UNNAMED
      - -cp
      - "@/app/jib-classpath-file"
      - org.snomed.snowstorm.SnowstormApplication
      - --elasticsearch.urls=http://elasticsearch:9200
    environment:
      # after you load RF2 into MAIN, this branch will become non-null
      - SNOMED_SERVER_BRANCH=MAIN
    ports:
      - "9100:8080"
    restart: always
