"""OpenMed Terminology Service.

A lightweight FastAPI service that provides two distinct capabilities:

1. **SNOMED term extraction** (``/batch``): uses a biomedical NER model
   (``d4data/biomedical-ner-all``) to extract medical entity names suitable
   for Snowstorm SNOMED CT lookup.

2. **Value description generation** (``/describe_batch``): uses a small
   instruction-tuned generative LLM (``Qwen/Qwen2.5-0.5B-Instruct``) to
   produce short, human-readable clinical descriptions from contextual
   prompts.  For example, the prompt
   ``"score 0 of 10 measuring Ability to use toilet"``
   is passed to the generative model which produces a description such as
   ``"Low ability to use toilet"`` or similar.

When either model cannot be loaded, the service falls back to simple
camelCase / snake_case text normalisation so it always returns a usable
result.
"""

import logging
import re
import time
from typing import Dict, List, Optional

from fastapi import FastAPI
from pydantic import BaseModel

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s - %(message)s",
)
logger = logging.getLogger("openmed")

# ---------------------------------------------------------------------------
# FastAPI app
# ---------------------------------------------------------------------------
app = FastAPI(
    title="OpenMed Terminology Service",
    description=(
        "Infers biomedical terminology search terms for dataset columns and values "
        "using the OpenMed NER model (OpenMed/OpenMed-NER-DiseaseDetect-SuperClinical-434M) "
        "with a text normalisation fallback.  Value descriptions are generated by "
        "OpenMeditron/Meditron3-Gemma2-2B, a medical LLM that produces precise "
        "clinical language such as 'Independent use of toilet' for Barthel ADL scores."
    ),
    version="1.0.0",
)

# ---------------------------------------------------------------------------
# Model management
# ---------------------------------------------------------------------------

# --- OpenMed NER model (used by /batch for SNOMED term extraction) ---
# OpenMed/OpenMed-NER-DiseaseDetect-SuperClinical-434M is a DeBERTa-based NER
# model trained on SuperClinical data to detect disease entities in biomedical
# text.  It extracts the clearest medical concept from a column name or value
# string so that Snowstorm can find the matching SNOMED CT concept.
NER_MODEL_NAME = "OpenMed/OpenMed-NER-DiseaseDetect-SuperClinical-434M"

# Minimum NER confidence score to accept an entity extraction.
# Below this threshold the service falls back to text normalisation.
MIN_CONFIDENCE_THRESHOLD: float = 0.50

_pipeline = None          # set to a callable on success, or "fallback" sentinel


def _load_model_once():
    """Load the HuggingFace NER pipeline (idempotent; thread-safe for the
    single startup call pattern FastAPI uses)."""
    global _pipeline
    if _pipeline is not None:
        return _pipeline

    try:
        from transformers import pipeline as hf_pipeline

        logger.info("[OpenMed] Loading biomedical NER model: %s", NER_MODEL_NAME)
        t0 = time.time()
        _pipeline = hf_pipeline(
            "ner",
            model=NER_MODEL_NAME,
            aggregation_strategy="first",   # "first" merges BPE sub-tokens into whole words
            device=-1,          # CPU only – avoids GPU dependency in tests
        )
        logger.info("[OpenMed] NER model loaded in %.1fs", time.time() - t0)

    except (ImportError, OSError, RuntimeError, EnvironmentError) as exc:
        logger.warning(
            "[OpenMed] Could not load NER model (%s: %s). "
            "Using text-normalisation fallback.",
            type(exc).__name__, exc,
        )
        _pipeline = "fallback"   # sentinel – means "use normalise() only"
    except Exception as exc:  # noqa: BLE001
        logger.warning(
            "[OpenMed] Unexpected error loading NER model (%s: %s). "
            "Using text-normalisation fallback.",
            type(exc).__name__, exc,
        )
        _pipeline = "fallback"

    return _pipeline


# --- Generative LLM (used by /describe_batch for description generation) ---
# OpenMeditron/Meditron3-Gemma2-2B is a Gemma2-based medical LLM fine-tuned on
# clinical data.  It produces precise clinical descriptions from contextual
# prompts, e.g.:
#   "score 0 of 10 measuring Ability to use toilet"  → "Unable to use toilet independently"
#   "score 10 of 10 measuring Ability to use toilet" → "Independent use of toilet"
#   "score 100 of 100 measuring Barthel index"       → "Full independence in ADL's"
DESCRIBE_MODEL_NAME = "OpenMeditron/Meditron3-Gemma2-2B"

_describe_pipeline = None   # set to (tokenizer, model) tuple on success, or "fallback"

# Meditron3-Gemma2-2B does not support a system role – instruction is embedded
# directly in the user turn.
_DESCRIBE_PROMPT_TEMPLATE = (
    'Clinical phrase: "{phrase}"\n'
    "Write a SHORT clinical description (2-6 words) for this phrase. "
    "Only output the description:"
)


def _load_describe_model_once():
    """Load the OpenMeditron generative LLM used to generate value descriptions.

    Returns a ``(tokenizer, model)`` tuple on success, or the string
    ``"fallback"`` when the model cannot be loaded.  The fallback path
    uses normalised phrase text as the description.
    """
    global _describe_pipeline
    if _describe_pipeline is not None:
        return _describe_pipeline

    try:
        import torch
        from transformers import AutoModelForCausalLM, AutoTokenizer

        logger.info("[OpenMed] Loading description model: %s", DESCRIBE_MODEL_NAME)
        t0 = time.time()
        tok = AutoTokenizer.from_pretrained(DESCRIBE_MODEL_NAME)
        mdl = AutoModelForCausalLM.from_pretrained(
            DESCRIBE_MODEL_NAME, dtype=torch.bfloat16
        )
        mdl.eval()
        _describe_pipeline = (tok, mdl)
        logger.info("[OpenMed] Description model loaded in %.1fs", time.time() - t0)

    except (ImportError, OSError, RuntimeError, EnvironmentError) as exc:
        logger.warning(
            "[OpenMed] Could not load description model (%s: %s). "
            "Using text-normalisation fallback.",
            type(exc).__name__, exc,
        )
        _describe_pipeline = "fallback"
    except Exception as exc:  # noqa: BLE001
        logger.warning(
            "[OpenMed] Unexpected error loading description model (%s: %s). "
            "Using text-normalisation fallback.",
            type(exc).__name__, exc,
        )
        _describe_pipeline = "fallback"

    return _describe_pipeline


def _generate_desc(prompt: str, pipe) -> str:
    """Generate a short clinical description from a contextual prompt.

    Uses OpenMeditron/Meditron3-Gemma2-2B, a medical LLM that produces precise
    clinical language from contextual phrases.

    Falls back to normalised prompt text when the model is unavailable.

    Examples (with model loaded)
    ----------------------------
    prompt="score 0 of 10 measuring Ability to use toilet"
      → "Unable to use toilet independently"

    prompt="score 10 of 10 measuring Ability to use toilet"
      → "Independent use of toilet"

    prompt="score 100 of 100 measuring Barthel index"
      → "Full independence in ADL's"

    prompt="Ischemic as a category of Stroke"
      → "Ischemic stroke"
    """
    if not prompt or not prompt.strip():
        return prompt or ""

    normalised = _normalise(prompt)

    if pipe is None or pipe == "fallback":
        return normalised

    try:
        import torch
        tok, mdl = pipe
        # Meditron3-Gemma2-2B does not support a system role; embed the
        # instruction directly in the user turn.
        user_content = _DESCRIBE_PROMPT_TEMPLATE.format(phrase=prompt.strip())
        msgs = [{"role": "user", "content": user_content}]
        text = tok.apply_chat_template(msgs, tokenize=False, add_generation_prompt=True)
        ids = tok([text], return_tensors="pt")
        with torch.no_grad():
            out = mdl.generate(**ids, max_new_tokens=20, do_sample=False)
        gen_ids = out[0][ids["input_ids"].shape[-1]:]
        result = tok.decode(gen_ids, skip_special_tokens=True).strip()
        # Trim to the first sentence/line.
        result = re.split(r"[\n.]", result)[0].strip()
        alpha_chars = sum(1 for c in result if c.isalpha())
        if result and alpha_chars >= 2:
            logger.debug("[OpenMed] Generated desc for '%s' → '%s'", prompt[:40], result)
            return result
    except Exception as exc:  # noqa: BLE001
        logger.warning("[OpenMed] Description generation error for '%s': %s", prompt[:40], exc)

    return normalised


# ---------------------------------------------------------------------------
# Request / response schemas
# ---------------------------------------------------------------------------

class ColumnInput(BaseModel):
    col_key: str
    values: List[str] = []


class BatchRequest(BaseModel):
    columns: List[ColumnInput]


class ColumnTerms(BaseModel):
    col_key: str
    col_search_term: str
    value_terms: Dict[str, str] = {}


class BatchResponse(BaseModel):
    columns: List[ColumnTerms]


# --- Description schemas ---

class ValueDescInput(BaseModel):
    v: str
    terminology_label: Optional[str] = None
    min: Optional[str] = None   # numeric range lower bound (from ValueSpec.min)
    max: Optional[str] = None   # numeric range upper bound (from ValueSpec.max)


class ColumnDescInput(BaseModel):
    col_key: str
    terminology_label: Optional[str] = None
    values: List[ValueDescInput] = []


class DescribeBatchRequest(BaseModel):
    columns: List[ColumnDescInput]


class ValueDesc(BaseModel):
    v: str
    d: str


class ColumnDesc(BaseModel):
    col_key: str
    col_desc: str
    values: List[ValueDesc] = []


class DescribeBatchResponse(BaseModel):
    columns: List[ColumnDesc]


# ---------------------------------------------------------------------------
# Inference helpers
# ---------------------------------------------------------------------------

def _normalise(text: str) -> str:
    """Split camelCase / snake_case tokens, lowercase and strip punctuation."""
    s = re.sub(r"([a-z])([A-Z])", r"\1 \2", text)   # camelCase → camel Case
    s = re.sub(r"[_\-]+", " ", s)                    # snake_case → snake case
    s = re.sub(r"\s+", " ", s)
    return s.strip().lower()


def _extract_label(terminology: str) -> str:
    """Extract a human-readable label from a terminology string.

    Handles three formats produced by the Snowstorm lookup pipeline:
    - New:    ``"Diabetes mellitus | 73211009"``  → ``"Diabetes mellitus"``
    - Legacy: ``"73211009|Diabetes mellitus"``     → ``"Diabetes mellitus"``
    - Plain:  ``"Hypertension"``                   → ``"Hypertension"``
    - Empty / None                                 → ``""``
    """
    t = (terminology or "").strip()
    if not t:
        return ""
    # New format: "label | code"
    sep = t.rfind(" | ")
    if sep > 0:
        label = t[:sep].strip()
        if label:
            return label
    # Legacy format: "code|label"
    bar = t.find("|")
    if 0 < bar < len(t) - 1:
        right = t[bar + 1:].strip()
        if right:
            return right
    return t


# ---------------------------------------------------------------------------
# Generic-column detection
# ---------------------------------------------------------------------------

_GENERIC_COL_RE = re.compile(
    r"^(col(?:umn)?|var(?:iable)?|field|attr(?:ribute)?|v|x|f)[\s_\-]?\d+$",
    re.IGNORECASE,
)


def _is_generic_column_name(name: str) -> bool:
    """Return True when *name* is a generic placeholder such as column_1 or var_2."""
    return bool(_GENERIC_COL_RE.match(name.strip()))


def _infer_col_from_values(col_key: str, values: List[str], pipe) -> str:
    """Infer a meaningful column search term when the column name is generic.

    Tries NER on the first few non-numeric, non-trivial values.  If NER produces
    a term that is clearly better than text normalisation, use it.  Otherwise
    falls back to normalising the column key itself.
    """
    candidates = [
        v.strip()
        for v in (values or [])
        if v and v.strip() and not re.match(r"^-?\d+(\.\d+)?$", v.strip())
        and len(v.strip()) >= 3
    ][:3]
    for candidate in candidates:
        norm = _normalise(candidate)
        term = _infer_term(candidate, pipe)
        alpha = sum(1 for c in term if c.isalpha())
        if alpha >= 2 and term != norm:
            logger.debug(
                "[OpenMed] Generic col '%s' inferred from value '%s' → '%s'",
                col_key,
                candidate,
                term,
            )
            return term
    return _normalise(col_key)


def _infer_term(text: str, pipe) -> str:
    """Return the best medical search term for *text*.

    Uses the OpenMed NER pipeline when available and the entity confidence meets
    ``MIN_CONFIDENCE_THRESHOLD``.  Falls back to text normalisation otherwise
    so the caller always receives a non-empty, meaningful search phrase.

    The text is normalised (camelCase → spaces, snake_case → spaces) before NER
    inference so that disease entities inside column names like "StrokeType" or
    "DiabetesMellitus" are correctly identified by the model.  Character-offset
    extraction is performed on the normalised text to avoid SentencePiece
    tokenizer artifacts (e.g. "Ischemicstroke" instead of "Ischemic stroke").
    """
    if not text or not text.strip():
        return text or ""

    normalised = _normalise(text)

    if pipe is None or pipe == "fallback":
        return normalised

    try:
        # Normalise first: "StrokeType" → "stroke type" so the NER model sees
        # proper word boundaries.  Title-case to match the model's training
        # distribution (clinical text is usually capitalised).
        query = normalised.title()
        entities = pipe(query[:256])
        if entities:
            # Pick the highest-confidence entity.
            best = max(entities, key=lambda e: e.get("score", 0.0))
            score: float = best.get("score", 0.0)

            if score < MIN_CONFIDENCE_THRESHOLD:
                logger.debug(
                    "[OpenMed] Low-confidence NER for '%s' (score=%.3f < %.3f); "
                    "using text normalisation fallback",
                    text[:40],
                    score,
                    MIN_CONFIDENCE_THRESHOLD,
                )
                return normalised

            # Prefer the original text span (start/end char offsets) over the
            # model's `word` token: DeBERTa/SentencePiece models may return
            # space-stripped tokens like "Ischemicstroke" instead of the
            # properly-spaced original "Ischemic stroke".
            raw = query
            start: int = best.get("start", 0)
            end: int = best.get("end", len(raw))
            span = raw[start:end].strip() if 0 <= start < end <= len(raw) else ""
            word = span if span else (best.get("word") or "").strip()
            # Reject artefacts: extracted span must have at least 2 alphabetic characters.
            alpha_chars = sum(1 for c in word if c.isalpha())
            if word and alpha_chars >= 2:
                logger.debug(
                    "[OpenMed] NER '%s' → '%s' (score=%.3f)",
                    text[:40],
                    word,
                    score,
                )
                return word

            logger.debug(
                "[OpenMed] NER word '%s' rejected (alpha_chars=%d); "
                "using normalisation fallback",
                word,
                alpha_chars,
            )
    except (ValueError, RuntimeError) as exc:
        logger.warning("[OpenMed] NER pipeline error for text='%s': %s", text[:40], exc)
    except Exception as exc:  # noqa: BLE001
        # Broad catch is intentional: the aggregated NER pipeline can surface
        # many unexpected exception types depending on the model, tokeniser and
        # aggregation strategy.  We always fall back to text normalisation.
        logger.warning("[OpenMed] Unexpected NER error for text='%s': %s", text[:40], exc)

    return normalised


def _infer_value_term(value: str, col_search_term: str, pipe) -> str:
    """Infer the best search term for a column *value*, using column context when needed.

    Rules (in priority order):

    1. **Numeric or very-short values** (< 3 non-space characters): combine with the
       column search term so Snowstorm can find scale-specific concepts.
       e.g.  col='Toilet', value='0'   →  'toilet 0'
             col='BarthelIndex', value='5' →  'barthel index 5'

    2. **Fallback mode** (NER model not loaded): return the normalised value directly.
       Long medical terms like "hypertension" are self-identifying in Snowstorm and
       must not be contaminated with column context when NER is unavailable.

    3. **Model mode – multi-word values** where NER gives the same result as normalisation
       (i.e. the value is not a recognised medical entity): enrich with column context.
       e.g.  col='Education', value='High school' (NER: no entity) →  'high school education'

    4. **All other values**: use the NER result as-is.

    The result is always a plain-text search phrase, never a SNOMED code.
    """
    v = (value or "").strip()
    if not v:
        return v

    col_ctx = (col_search_term or "").strip().lower()

    # Rule 1 – numeric or very short: always prepend column context
    is_numeric = bool(re.match(r"^-?\d+(\.\d+)?$", v))
    is_very_short = len(v.replace(" ", "")) < 3
    if is_numeric or is_very_short:
        if col_ctx:
            result = f"{col_ctx} {v}"
            logger.debug(
                "[OpenMed] Short/numeric value '%s' enriched with col context → '%s'",
                v,
                result,
            )
            return result
        return _normalise(v)

    # Rule 2 – fallback mode: return plain normalised form; do not add column context.
    # Medical terms are self-identifying in Snowstorm; contaminating them with the
    # column name would produce multi-word phrases that rarely match any concept
    # (e.g. "hypertension diagnosis" instead of "hypertension").
    if pipe is None or pipe == "fallback":
        return _normalise(v)

    # Rule 3/4 – model IS loaded: run NER, enrich only when NER gives no improvement
    normalised = _normalise(v)
    term = _infer_term(v, pipe)

    # Enrich with column context only for phrases of 3+ words where NER couldn't find
    # a specific entity.  Two-word medical terms ("diabetes mellitus", "myocardial
    # infarction", "high school") are self-identifying in Snowstorm; contaminating
    # them with the column name hurts recall.
    if term == normalised and col_ctx and len(v.split()) >= 3:
        enriched = f"{normalised} {col_ctx}"
        logger.debug(
            "[OpenMed] Multi-word value '%s' enriched with col context → '%s'",
            v,
            enriched,
        )
        return enriched

    return term or normalised


# ---------------------------------------------------------------------------
# Application lifecycle
# ---------------------------------------------------------------------------

@app.on_event("startup")
async def startup_event():
    logger.info("[OpenMed] Service starting up – pre-loading models …")
    _load_model_once()
    _load_describe_model_once()
    logger.info("[OpenMed] Ready.")


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@app.get("/health")
async def health():
    """Liveness / readiness probe."""
    pipe = _pipeline
    model_loaded = pipe is not None and pipe != "fallback"
    describe_pipe = _describe_pipeline
    describe_loaded = describe_pipe is not None and describe_pipe != "fallback"
    return {
        "status": "ok",
        "ner_model": NER_MODEL_NAME,
        "ner_model_loaded": model_loaded,
        "describe_model": DESCRIBE_MODEL_NAME,
        "describe_model_loaded": describe_loaded,
        "mode": ("ner+generative" if model_loaded and describe_loaded
                 else "ner" if model_loaded
                 else "generative" if describe_loaded
                 else "fallback"),
    }


@app.post("/infer_batch", response_model=BatchResponse)
async def infer_batch(request: BatchRequest):
    """Infer SNOMED-searchable terminology for a batch of columns.

    For each ``ColumnInput``:
    - Suggest a ``col_search_term`` for the column header itself.
    - Suggest a search term for every distinct value.

    Uses a biomedical NER model when available; falls back to camelCase /
    snake_case normalisation otherwise.
    """
    pipe = _load_model_once()
    t0 = time.time()
    logger.info("[OpenMed] /infer_batch – %d columns", len(request.columns))

    results: List[ColumnTerms] = []
    for col in request.columns:
        col_key = (col.col_key or "").strip()
        if not col_key:
            logger.warning("[OpenMed] Skipping column with empty col_key")
            continue

        # For generic placeholder names (column_1, var_2, …) try to infer from values.
        if _is_generic_column_name(col_key):
            col_term = _infer_col_from_values(col_key, col.values, pipe) or col_key
        else:
            col_term = _infer_term(col_key, pipe) or col_key

        value_terms: Dict[str, str] = {}
        for raw_val in col.values:
            v = (raw_val or "").strip()
            if v:
                # Always pass the column search term so numeric / short values
                # receive meaningful context (e.g. "toilet 0", "barthel index 5").
                value_terms[v] = _infer_value_term(v, col_term, pipe) or v

        results.append(
            ColumnTerms(
                col_key=col_key,
                col_search_term=col_term,
                value_terms=value_terms,
            )
        )

    elapsed = time.time() - t0
    logger.info("[OpenMed] Inferred %d column(s) in %.2fs", len(results), elapsed)
    return BatchResponse(columns=results)


# ---------------------------------------------------------------------------
# Description helpers
# ---------------------------------------------------------------------------

def _sentence(text: str, fallback: str = "field") -> str:
    """Capitalise and ensure the text ends with a full stop."""
    s = (text or "").strip() or fallback.strip() or "field"
    if s.startswith('"') and s.endswith('"') and len(s) >= 2:
        s = s[1:-1].strip()
    s = s[:1].upper() + s[1:] if s else s
    if s and s[-1] not in ".!?":
        s += "."
    return s


def _build_value_phrase(
    v: str,
    col_label: str,
    scale_min: Optional[float],
    scale_max: Optional[float],
) -> str:
    """Build a contextual prompt for a **numeric** value to pass to the model.

    Only uses the word "score" when an explicit ordinal scale range (min/max) is
    known.  Without scale bounds the value could be a category code (e.g. 0=No,
    1=Yes), so a neutral phrasing is used instead.

    The phrase is intended as the model's **input prompt**.  The model processes
    it and generates the clinical description (e.g. "dependent", "independent").
    In fallback mode (no model) the normalised phrase itself is returned as the
    description.

    Examples
    --------
    col_label="Ability to use toilet", v="0", min=0, max=10
      → "score 0 of 10 measuring Ability to use toilet"

    col_label="Barthel index", v="50", min=0, max=100
      → "score 50 of 100 measuring Barthel index"

    col_label="Gender", v="1", no scale   (category code)
      → "1 as a value of Gender"
    """
    label = (col_label or "").strip()

    if scale_min is not None and scale_max is not None and scale_max > scale_min:
        max_str = str(int(scale_max)) if scale_max == int(scale_max) else str(scale_max)
        if label:
            return f"score {v} of {max_str} measuring {label}"
        return f"score {v} of {max_str}"

    # No scale bounds → may be a category code; use neutral phrasing
    if label:
        return f"{v} as a value of {label}"
    return f"value {v}"


def _build_category_phrase(v: str, col_label: str) -> str:
    """Build a contextual prompt for a **text/categorical** value to pass to the model.

    The phrase identifies the value as a category of the column concept so the
    model can infer the appropriate clinical description without any hardcoded
    term mappings.

    The phrase is intended as the model's **input prompt**.  In fallback mode
    the normalised phrase is used as the description.

    Examples
    --------
    col_label="Stroke", v="Ischemic"
      → "Ischemic as a category of Stroke"

    col_label="Gender", v="Male"
      → "Male as a category of Gender"
    """
    label = (col_label or "").strip()
    if label:
        return f"{v} as a category of {label}"
    return v


@app.post("/describe_batch", response_model=DescribeBatchResponse)
async def describe_batch(request: DescribeBatchRequest):
    """Generate plain-language descriptions for column headers and their values.

    For each ``ColumnDescInput``:

    - **col_desc**: SNOMED terminology label when available; otherwise normalise
      the column key.
    - **values[i].d**:
        1. If a SNOMED terminology label is provided for the value, use it directly.
        2. If the value is numeric **and** scale bounds (min/max) are known, build
           an ordinal score prompt and pass it to the generative LLM:
           ``"score {v} of {max} measuring {col_label}"``
        3. If the value is numeric **without** scale bounds (could be a category
           code), build a neutral value prompt and pass it to the generative LLM:
           ``"{v} as a value of {col_label}"``
        4. If the value is text/categorical, build a category prompt and pass it
           to the generative LLM: ``"{v} as a category of {col_label}"``

    In all cases the contextual phrase is the **generative LLM's input prompt**.
    The LLM produces the clinical description (e.g. "Low ability to use toilet",
    "Ischemic stroke", "Male gender").  When the generative model is unavailable
    the normalised prompt phrase is returned as a fallback description.
    """
    describe_pipe = _load_describe_model_once()
    t0 = time.time()
    logger.info("[OpenMed] /describe_batch – %d columns", len(request.columns))

    results: List[ColumnDesc] = []
    for col in request.columns:
        col_key = (col.col_key or "").strip()
        if not col_key:
            continue

        # Column description: extract plain label from SNOMED string, then normalise col_key
        term_label = _extract_label(col.terminology_label or "")
        col_desc_raw = term_label if term_label else _normalise(col_key)
        col_desc = _sentence(col_desc_raw, col_key)

        value_descs: List[ValueDesc] = []
        for val_info in (col.values or []):
            v = (val_info.v or "").strip()
            if not v:
                continue

            val_term = _extract_label(val_info.terminology_label or "")
            if val_term:
                # SNOMED label available – use it directly, no model call needed.
                d = _sentence(val_term, v)

            elif re.match(r"^-?\d+(\.\d+)?$", v):
                # Numeric value: build a contextual prompt and pass it to the
                # generative LLM.  Use "score" phrasing only when scale bounds
                # are known; without them the value may be a category code.
                scale_min: Optional[float] = None
                scale_max: Optional[float] = None
                try:
                    if val_info.min is not None:
                        scale_min = float(val_info.min)
                    if val_info.max is not None:
                        scale_max = float(val_info.max)
                except (ValueError, TypeError):
                    pass
                prompt = _build_value_phrase(v, col_desc_raw, scale_min, scale_max)
                generated = _generate_desc(prompt, describe_pipe)
                d = _sentence(generated if generated else prompt, v)

            else:
                # Text/categorical value: build a category prompt and pass it to
                # the generative LLM.
                prompt = _build_category_phrase(v, col_desc_raw)
                generated = _generate_desc(prompt, describe_pipe)
                d = _sentence(generated if generated else _normalise(v), v)

            value_descs.append(ValueDesc(v=v, d=d))

        results.append(ColumnDesc(
            col_key=col_key,
            col_desc=col_desc,
            values=value_descs,
        ))

    elapsed = time.time() - t0
    logger.info("[OpenMed] Described %d column(s) in %.2fs", len(results), elapsed)
    return DescribeBatchResponse(columns=results)
