[libdefaults]
    default_realm = TANIWHA-REALM
    udp_preference_limit = 4096
    kdc_tcp_port = 8089
    kdc_udp_port = 8089
    allow_weak_crypto = true
    default_tkt_enctypes = aes256-cts-hmac-sha1-96 aes128-cts-hmac-sha1-96
    default_tgs_enctypes = aes256-cts-hmac-sha1-96 aes128-cts-hmac-sha1-96
    permitted_enctypes = aes256-cts-hmac-sha1-96 aes128-cts-hmac-sha1-96
    dns_lookup_realm = false
    dns_lookup_kdc = false
    ticket_lifetime = 24h
    renew_lifetime = 7d
    forwardable = true

[realms]
    TANIWHA-REALM = {
        kdc = localhost:8089
    }

[domain_realm]
    .localhost = TANIWHA-REALM
    localhost = TANIWHA-REALM
